//=======================================================
// score_tree.v
// Sparse sliding-window frontend plus parameterized MAC tree.
//
// This is the straightforward datapath:
//   row_pixels -> column shift window -> sparse tap gather -> MAC tree
//
// Template tap format:
//   { row[ROW_W-1:0], col[COL_W-1:0], signed weight[WEIGHT_W-1:0] }
//
// Coordinate convention:
//   tap row/col are top-left template coordinates, matching make_templates.py.
//   The incoming row_pixels bus is also top-to-bottom.  The column shift
//   register stores current column at index 0, so template col is reversed
//   internally when the sample is gathered.
//
// The included .vh file is selected by the TEMPLATE_INCLUDE macro.  If the
// macro is not defined, the donut template generated by make_templates.py is
// used by default.
//=======================================================
`ifndef TEMPLATE_INCLUDE
`define TEMPLATE_INCLUDE "cow_edge_template_64.vh"
`endif

module score_tree #(
    parameter NUM_ROWS  = 32,
    parameter NUM_COLS  = 32,
    parameter NUM_TAPS  = 64,
    parameter ROW_W     = 5,
    parameter COL_W     = 5,
    parameter FEATURE_W = 8,
    parameter WEIGHT_W  = 8,
    parameter SCORE_W   = 32
)(
    input                          clk,
    input                          rst_n,

    // Shift row_pixels into the column window when row_pixels_valid is high.
    input                          row_pixels_valid,
    input      [NUM_ROWS*FEATURE_W-1:0] row_pixels,

    // Assert when row_pixels contains a complete NUM_ROWS x NUM_COLS window.
    input                          in_valid,

    output signed [SCORE_W-1:0]    score_out,
    output                         score_valid
);

    localparam TAP_W = ROW_W + COL_W + WEIGHT_W;

    wire [TAP_W-1:0] tap_data [0:NUM_TAPS-1];
    `include `TEMPLATE_INCLUDE

    wire [ROW_W-1:0]             t_row    [0:NUM_TAPS-1];
    wire [COL_W-1:0]             t_col    [0:NUM_TAPS-1];
    wire [COL_W-1:0]             t_col_sr [0:NUM_TAPS-1];
    wire signed [WEIGHT_W-1:0]   t_weight [0:NUM_TAPS-1];

    genvar t;
    generate
        for (t = 0; t < NUM_TAPS; t = t + 1) begin : tap_decode
            assign t_row[t]    = tap_data[t][TAP_W-1 -: ROW_W];
            assign t_col[t]    = tap_data[t][WEIGHT_W+COL_W-1 -: COL_W];
            assign t_weight[t] = tap_data[t][WEIGHT_W-1:0];

            // Shift-register column 0 is the newest/current column.  Template
            // column 0 is the oldest/leftmost column of the window.
            assign t_col_sr[t] = (NUM_COLS - 1) - t_col[t];
        end
    endgenerate

    wire [FEATURE_W-1:0] rp [0:NUM_ROWS-1];
    generate
        for (t = 0; t < NUM_ROWS; t = t + 1) begin : unpack_rows
            assign rp[t] = row_pixels[t*FEATURE_W +: FEATURE_W];
        end
    endgenerate

    reg [FEATURE_W-1:0] sr [0:NUM_ROWS-1][0:NUM_COLS-1];

    integer r, c;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            for (r = 0; r < NUM_ROWS; r = r + 1)
                for (c = 0; c < NUM_COLS; c = c + 1)
                    sr[r][c] <= {FEATURE_W{1'b0}};
        end else if (row_pixels_valid) begin
            for (r = 0; r < NUM_ROWS; r = r + 1) begin
                sr[r][0] <= rp[r];
                for (c = 1; c < NUM_COLS; c = c + 1)
                    sr[r][c] <= sr[r][c-1];
            end
        end
    end

    // One-cycle delay lets sr capture the newest row_pixels before the MAC tree
    // samples the complete sparse window.
    reg in_valid_d;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            in_valid_d <= 1'b0;
        else
            in_valid_d <= in_valid;
    end

    wire [NUM_TAPS*FEATURE_W-1:0] features_for_mac;
    wire [NUM_TAPS*WEIGHT_W-1:0]  weights_for_mac;

    generate
        for (t = 0; t < NUM_TAPS; t = t + 1) begin : gather_taps
            assign features_for_mac[t*FEATURE_W +: FEATURE_W] = sr[t_row[t]][t_col_sr[t]];
            assign weights_for_mac[t*WEIGHT_W +: WEIGHT_W]    = t_weight[t];
        end
    endgenerate

    score_mac_tree #(
        .NUM_TAPS  ( NUM_TAPS  ),
        .FEATURE_W ( FEATURE_W ),
        .WEIGHT_W  ( WEIGHT_W  ),
        .SCORE_W   ( SCORE_W   )
    ) u_mac_tree (
        .clk         ( clk             ),
        .rst_n       ( rst_n           ),
        .features    ( features_for_mac),
        .weights     ( weights_for_mac ),
        .in_valid    ( in_valid_d      ),
        .score_out   ( score_out       ),
        .score_valid ( score_valid     )
    );

endmodule
